
CREATE TABLE USERS (
    USER_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(15) NOT NULL,
    EMAIL_ID VARCHAR(40) NOT NULL,
    MOBILE_NUMBER VARCHAR(13) NOT NULL,
    USER_PROFILE_IMG VARCHAR(255),
    DOB DATE NOT NULL,
    STATUS INT(1) DEFAULT 1,
    CREATED_DTTM DATETIME NOT NULL,
    MODIFIED_DTTM DATETIME,
    UNIQUE (USERNAME, EMAIL_ID)
);